title: POMB
email: hello@pomb.com.br
# baseurl: "http://pomb.com.br/dev"

markdown: kramdown

collections:
  paginas:
    output: true
  trabalhos:
    output: true
  exposicoes:
    output: true
  rascunhos:
    output: false
  main-pages:
    output: true
  works:
    output: true
  exhibitions:
    output: true
  drafts:
    output: false
prose:
  ignore:
    - /_exhibitions
    - /_includes
    - /_layouts
    - /_main-pages
    - /_paginas
    - /_sass
    - /_works
    - /css
    - /scripts
    - index.html
    - _config.yml
    - CNAME
  siteurl: "http://pomb.com.br"
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "text"
          value: "post"
      - name: "date"
        field:
          label: "data"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "autor"
          element: "text"
          value: "POMB"
      - name: "categories"
        field:
          label: "categorias"
          element: "text"
          placeholder: "Designe categorias"
      - name: "excerpt"
        field:
          label: "excerto"
          element: "text"
          placeholder: "Coloque um resumo"
      - name: "meta"
        field:
          label: "metadados"
          element: "text"
          placeholder: "Coloque os metadados"