title: POMB
email: hello@pomb.com.br
# baseurl: "http://pomb.com.br/dev"

markdown: kramdown

collections:
  paginas:
    output: true
  trabalhos:
    output: true
  exposicoes:
    output: true
  rascunhos:
    output: false
  main-pages:
    output: true
  works:
    output: false
  exhibitions:
    output: false
  drafts:
    output: false
prose:
  media: "img"
  siteurl: "http://pomb.com.br"
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "Layout"
          element: hidden
          value: "post"
      - name: "date"
        field:
          label: "Data"
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "author"
        field:
          label: "Autor"
          element: "text"
          value: "POMB"
      - name: "categories"
        field:
          label: "Categorias"
          element: "text"
          placeholder: "Categorias"
      - name: "excerpt"
        field:
          label: "Excerto"
          element: "text"
          placeholder: "Excerto"
      - name: "meta"
        field:
          label: "Metadados"
          element: "text"
          placeholder: "Metadados"
    _trabalhos:
      - name: "layout"
        field:
          label: "Layout"
          element: hidden
          value: "projeto"
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "Ex.: trabalhos/novo-projeto"
      - name: "description"
        field:
          label: "Descrição"
          element: "textarea"
          placeholder: "Descrição do projeto"
    _exposicoes:
      - name: "layout"
        field:
          label: "Layout"
          element: hidden
          value: "projeto"
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          placeholder: "Ex.: exposicoes/novo-projeto"
      - name: "description"
        field:
          label: "Descrição"
          element: "textarea"
          placeholder: "Um resumo da exposição"
      - name: "exhibition_date"
        field:
          label: "Data da exposição"
          element: "text"
          placeholder: "Ex.: 12/12/2014 a 15/01/2015"
      - name: "exhibition_location"
        field:
          label: "Local da exposição"
          element: "text"
          placeholder: "Ex.: Sesc 504 Sul – Brasília"
  ignore:
    - /_exhibitions
    - /_includes
    - /_layouts
    - /_main-pages
    - /_sass
    - /_works
    - /css
    - /scripts
    - index.html
    - _config.yml
    - CNAME
    - .gitignore
    - android-chrome-36x36.png
    - android-chrome-48x48.png
    - android-chrome-72x72.png
    - android-chrome-96x96.png
    - android-chrome-144x144.png
    - android-chrome-192x192.png
    - apple-touch-icon-57x57.png
    - apple-touch-icon-60x60.png
    - apple-touch-icon-72x72.png
    - apple-touch-icon-76x76.png
    - apple-touch-icon-114x114.png
    - apple-touch-icon-120x120.png
    - apple-touch-icon-144x144.png
    - apple-touch-icon-152x152.png
    - apple-touch-icon-180x180.png
    - apple-touch-icon-precomposed.png
    - apple-touch-icon.png
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon-96x96.png
    - favicon-194x194.png
    - favicon.ico
    - mstile-70x70.png
    - mstile-144x144.png
    - mstile-150x150.png
    - mstile-310x150.png
    - mstile-150x310.png
    - mstile-310x310.png
    - safari-pinned-tab.svg