# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Site do POMB
email: hello@pomb.com.br
description: Parabéns! Você chegou aqui mesmo antes de a página "em construção" estar pronta! Aguarde só mais um pouquinho. E depois mais um pouquinho pra ver o site maneiro que estamos preparando :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pomb.com.br" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
