title: POMB
email: hello@pomb.com.br
# baseurl: "http://pomb.com.br/dev"

markdown: kramdown

collections:
  main-pages:
    output: true
  work:
    output: true
  exhibition:
    output: true
  work-soon:
    output: false